config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'

  devise_for :users

  resources :users do
    resources :lodgings
    # resources :bookings, only: :index
  end

  resources :lodgings, only: :index do
    resources :bookings, only: [:new, :create]
    resources :locations, only: :index
  end

  match('/search', { :via => :get, :to => 'lodgings#search' } )
  match('/legal', {:via => :get, :to => 'application#legal' } )
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :lodging

  before_save :calc_bill

  def count_nights
    (end_date - start_date).to_i
  end

private

  def calc_bill
    self.bill = count_nights * Lodging.find(lodging_id).cost
  end
end

app/models/location.rb
class Location # < ActiveRecord::Base

  def self.all(location_name)
    Lodging.where(location: location_name)
  end

end

app/models/lodging.rb
class Lodging < ActiveRecord::Base
  validates_presence_of :location
  validates_presence_of :name
  validates_presence_of :marketing_text
  validates_presence_of :cost
  belongs_to :user
  has_many :bookings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lodgings
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index

  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @user = current_user
    @lodging = Lodging.find(params[:lodging_id])
    @booking = @lodging.bookings.new
  end

  def create
    @user = current_user
    @lodging = Lodging.find(params[:lodging_id])
    @booking = @lodging.bookings.new(booking_params)
    if @booking.save
      respond_to { |format| format.js }
      flash[:notice] = "Succesfully Booked Your Room: Cost $#{@booking.bill}"
    else
      render('new')
    end
  end

private
  def booking_params
    params.require(:booking).permit(:user_id, :bill, :start_date, :end_date)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @lodgings = Location.all(Lodging.find(params[:lodging_id]).location)
  end

end

app/controllers/lodgings_controller.rb
class LodgingsController < ApplicationController
  before_action :all_lodgings, only: :index

  # removed index because ^^^^ does what it did, and view is auto-rendered

  def show
    @lodging = Lodging.find(params[:id])
  end

  #### AJAX THIS UP!

  def new
    @user = current_user
    @lodging = @user.lodgings.new
  end

  def create
    @lodging = current_user.lodgings.new(lodgings_params)
    if @lodging.save
      respond_to { |format| format.js }
    else
      render('new')
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @lodging = Lodging.find(params[:id])
  end

  def update

  end


  def destroy

  end

  def search
    @search_text = params[:search_term]
    @search_results = Lodging.basic_search(@search_text)
    render('search/results.html.erb')
  end

private

  def lodgings_params
    params.require(:lodging).permit(:location, :cost, :name, :marketing_text)
  end

  def all_lodgings
    @lodgings = Lodging.all
  end
end

app/controllers/searches_controller.rb
def SearchesController < ApplicationController
  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @lodging = Lodging.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<div class="no-background">
  <h1 id="home-title">WELCOME TO WESTEROS</h1>

  <% if !current_user %>
    <%= link_to "Take the <strong style='color: black;'>Black</strong>, TODAY!".html_safe, new_user_registration_path, class: "btn btn-danger btn-lg" %>
  <% end %>
  <script>
    $('#landing-content').mousemove(function(e){
      var amountMovedX = (e.pageX * - 1 / 60);
      var amountMovedY = (e.pageY * - 1 / 60);
      $(this).css('background-position', amountMovedX + 'px ' + amountMovedY + 'px');
    });
  </script>
</div>

app/views/application/legal.html.erb
<div class="container">
  <div class="form-background">
    <h1>GUEST RIGHT</h1>
    <p><em>ALL</em> hosts and guests must honor this ancient right:</p>
    <p><blockquote>Guest right is an ancient and sacred tradition in Westeros. When a guest, be he common born or noble, eats the food and drinks the drink off a host's table beneath the host's roof, the guest right is invoked. Once invoked, neither the guest can harm his host nor the host harm his guest for the length of the guest's stay.</blockquote></p>

    <%= image_tag "dancingimp.gif", :id => 'tyrion' %>
  </div>
</div>

app/views/bookings/_form.html.erb
<%= form_for [@lodging, @booking], remote: true do |f| %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.label :start_date %>
  <%= f.date_select :start_date %>
  <%= f.label :end_date %>
  <%= f.date_select :end_date %>
  <%= f.submit "Submit", class: 'btn btn-success' %>
<% end %>

app/views/bookings/create.js.erb
$('#bookings-form').html('<p> <%= link_to "BOOK A ROOM", new_lodging_booking_path(@lodging), remote: true, class: "btn btn-success" %></p> <p>Succesfully booked <%= @booking.count_nights %> nights for $<%= @booking.bill %> </p>'
);

app/views/bookings/new.js.erb
$('#bookings-form').html("<%= j render 'form' %>");

app/views/layouts/_error.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav role="navigation" class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">MEAT & MEAD</a>
    </div>
    <!-- Collection of nav links, forms, and other content for toggling -->
    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <%= current_user ? current_user.email : "Account" %>
                <b class="caret"></b></a>
                <ul role="menu" class="dropdown-menu">
                    <% if !current_user %>
                        <li><%= link_to '[REGISTER] Swear Fealty', new_user_registration_path %></li>
                        <li><%= link_to '[LOGIN] Do Your Duty', new_user_session_path %></li>
                        <li><%= link_to '[FORGOT PW] Too much mead?', new_user_password_path %></li>
                    <% else %>
                        <li><%= link_to "[USER SHOW] Your Virtual Castle", user_path(current_user) %></li>
                        <li><%= link_to '[EDIT] Change Your Face', edit_user_registration_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to '[LOGOUT] Take the Black', destroy_user_session_path, method: :delete %></li>
                    <% end %>
                    <li class="divider"></li>
                </ul>
            </li>
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">DESTINATIONS <b class="caret"></b></a>
                <ul role="menu" class="dropdown-menu">
                    <li><%= link_to "Available Lodging", lodgings_path %></li>
                    <li class="divider"></li>
                    <% lodgings = Lodging.all %>
                    <% unique_lodgings = []  %>
                    <% lodgings.each_with_index do |lodge, index|   %>
                        <% unique_lodgings << lodge unless lodgings.slice(0, index).include?(lodge.name) || index == 0  %>
                    <% end %>
                    <% unique_lodgings.each do |location| %>
                        <li><%= link_to location.location, lodging_locations_path(location) %></li>
                    <% end %>
                </ul>
            </li>
        </ul>

        <form role="search" class="navbar-form navbar-left" action="/search">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search" name="search_term" id="search-term">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        </form>

        <ul class="nav navbar-nav navbar-right">
            <li><a href="/">Home Page</a></li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meatandmead</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render('layouts/navbar') %>
<div id="landing-content">
  <div class="container">
    <p class="notice"><%= flash[:notice] %></p>
    <p class="alert"><%= flash[:alert] %></p>
  </div>

  <div class="container">
    <%= yield %>
  </div>
  </div>
</div>

<div class="footer">
  <div class="container form-background">
    <p class="text-muted">All hosts extend and must abide by the ancient tradition of <%= link_to "Guest Right", "/legal" %></p>
  </div>
</div>


</body>

</html>

app/views/locations/index.html.erb
<div class="form-background">

  <h1>Visit <%= @lodgings[0].location %>!</h1>
  <ul>
    <% @lodgings.each do |location| %>
      <li><%= link_to location.name, user_lodging_path(User.find(location.user_id), location) %></li>
    <% end %>
  </ul>

</div>

app/views/lodgings/_form.html.erb
<%= form_for [@user, @lodging], remote: true do |f| %>
  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :cost %>
    <%= f.number_field :cost %>
  </div>

  <div class="form-group">
    <%= f.label :marketing_text %>
    <%= f.text_area :marketing_text, :rows => 20, :cols => 60 %>
  </div>

  <%= f.submit %>
<% end %>

app/views/lodgings/create.js.erb
$('form').hide();
$('#add_lodging_btn').show();

app/views/lodgings/index.html.erb
<div class="form-background">
  <h1>All Lodging</h1>

  <ul>
    <% @lodgings.order(:location).each do |lodging| %>
      <li><%= link_to "#{lodging.location}: #{lodging.name}", user_lodging_path(User.find(lodging.user_id), lodging)  %></li>
    <% end %>
  </ul>
</div>

app/views/lodgings/new.js.erb
$('form').detach();
$("#add_lodging_btn").hide();
$("#new_lodging_form").append("<%= j render('form') %>");

app/views/lodgings/show.html.erb
<div class="form-background">
  <h1><%= @lodging.name %> at <%= @lodging.location %></h1>

  <h2>Description</h2>

  <h3>Price: <%= @lodging.cost %></h3>
  <p><blockquote><%= @lodging.marketing_text %></blockquote></p>

  <div id="bookings-form">
    <% if current_user %>
      <p><%= link_to "BOOK A ROOM", new_lodging_booking_path(@lodging), remote: true, class: "btn btn-success" %></p>
    <% else %>
      <p><%= link_to "LOG IN TO BOOK A ROOM", new_user_session_path, class: "btn btn-success" %></p>
    <% end %>
  </div>
</div>

app/views/search/results.html.erb
<div class = "form-background">
  <h1>Search results for: <%= @search_text %></h1>

  <ul>
    <% @search_results.order(:location).each do |result| %>
      <li> <%= result.location %> - <%= link_to result.name, user_lodging_path(User.find(result.user_id), result) %> Cost Per Night: $ <%= result.cost %> </li>
    <% end %>
  </ul>

</div>

app/views/users/new.html.erb
<h1>SIGN UP</h1>

<%= render('layouts/error'), object: @user %>
<%= render('form') %>

app/views/users/show.html.erb
<div class="form-background">
  <h1><%= @user.email %></h1>


  <div id="new_lodging_form">
    <div id="add_lodging_btn">
      <%= link_to "Add Lodging", new_user_lodging_path(current_user), class: "btn btn-success", id: "add_lodging_btn_a", remote: true %>
    </div>
  </div>

  <div id = "user-bio">
    <% if @user.bio %>
      <blockquote><%= @user.bio %></blockquote>
    <% end %>
  </div>

  <div id="user_lodging_list">

    <h2><%= @user.email %> is Currently Hosting At:</h2>
    <ul>
      <% @user.lodgings.each do |lodging| %>
        <li><%= link_to lodging.name, user_lodging_path(@user, lodging) %> at <%= lodging.location %></li>
      <% end %>
    </ul>
  </div>

  <% if current_user == @user %>
    <h2>Your Vacations!</h2>
    <div id="user_vacations">
      <% @user.bookings.order(:start_date).each do |booking| %>
        <li><%= booking.lodging.location + ", staying at " + booking.lodging.name + " from: " + booking.start_date.to_s + " to " + booking.end_date.to_s %></li>
      <% end %>
    </div>
  <% end %>
  </div>
</div>